export const sneedexUrl = 'https://sneedex.moe/api'
export const toshoUrl = 'https://feed.animetosho.org/json'
export const animebytesUrl = 'https://animebytes.tv/scrape.php'
export const rutrackerUrl = 'http://api.rutracker.org/v1'
export const nyaaUrl = 'https://nyaa.sihttps://nyaa.si/?page=rss'
